name: main
on:
  push:
  
  schedule:
    - cron:  '0 0,5,10,15,20 * * *'


jobs:
  task:
    name: DyTool
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      
      - name: Run Automation Task
        run: |
          python ./hongbao.py

      - name: Run Task Sleep
        run: |
          python ./sleep.py

      # Commits all changed files to the repository
      - name: Commit to the repo
        run: |
          git config --global user.name "dytool"
          git config --global user.email "shimmeradanTemp02@snapmail.cc"
          git add .
          # "echo" returns true so the build succeeds, even if no changed files
          git commit -m 'Update'
          git push
